apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: default
  source:
    chart: jetstack/cert-manager
    repoURL: https://charts.jetstack.io
    targetRevision: 1.6.0
    helm:
      releaseName: cert-manager
      values: |
        global:
          create: true
        serviceAccount:
         create: true
        ingressShim:
          defaultIssuerName: letsencrypt-prod
          defaultIssuerKind: ClusterIssuer         
        installCRDs: true
        extraArgs:
          - "--leader-elect=false"       
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: kube-ingress