apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns-{{ .Values.spec.destination.name }}
  namespace: argocd
spec:
  project: default
  source:
    path: charts/external-dns
    repoURL: https://github.com/bbenlazreg/k8s-release.git
    targetRevision: HEAD
    helm:
      values: |
       external-dns:
        provider: {{ .Values.external-dns.provider }}
        policy: {{ default "sync"  .Values.external-dns.policy}}
        registry: txt
        txtOwnerId: {{ default "soundhound" .Values.external-dns.txtOwnerId}}
        logLevel: debug
        {{- if eq .Values.external-dns.provider "oci" }}
        image:
          registry: phx.ocir.io
          repository: axowjpy794t2/sre-devops/external-dns
          tag: 1.2.2
          pullSecrets:
            - image-pull
        {{- end }}
        sources:
          - service
          - ingress
        domainFilters:
          {{- range .Values.external-dns.domains }}
          - {{ . }}
          {{- end }}
        {{- if hasKey .Values "azure" }}
        azure:
          {{- if hasKey .Values.external-dns.azure "cloud" }}
          cloud: {{ .Values.external-dns.azure.cloud }}
          {{- end }}
          resourceGroup: {{ .Values.external-dns.azure.resourceGroup }}
          tenantId: ref+vault://secret/k8s/{{ $.Name }}#credentials.azure.tenant_id
          subscriptionId: ref+vault://secret/k8s/{{ $.Name }}#credentials.azure.subscription_id
          aadClientId: ref+vault://secret/k8s/{{ $.Name }}#credentials.azure.client_id
          aadClientSecret: ref+vault://secret/k8s/{{ $.Name }}#credentials.azure.client_secret
        {{- end }}
        {{- if hasKey .Values "google" }}
        google:
          project: {{ .Values.external-dns.google.project }}
          serviceAccountKey: ref+vault://secret/k8s/{{ $.Name }}/apps/external-dns#/serviceAccountContent
        {{- end }}
        {{- if eq .Values.external-dns.provider "oci" }}
        extraVolumeMounts:
          - name: config
            mountPath: /etc/kubernetes/
        extraVolumes:
          - name: config
            secret:
              secretName: oci-external-dns-auth
        {{- end }}

  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: kube-ingress
  syncPolicy:
    syncOptions:
    - CreateNamespace=true   