apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    app.kubernetes.io/instance: env1-k8s-base-services-test
  name: cert-manager-test
  namespace: argocd
spec:
  destination:
    namespace: kube-ingress-test
    server: 'https://152.70.130.252:6443'
  project: default
  source:
    chart: cert-manager
    helm:
      releaseName: cert-manager
      values: |
        global:
          create: true
        serviceAccount:
         create: true
        ingressShim:
          defaultIssuerName: letsencrypt-prod
          defaultIssuerKind: ClusterIssuer         
        installCRDs: true
        extraArgs:
          - "--leader-elect=false"       
    repoURL: 'https://charts.jetstack.io'
    targetRevision: 1.6.0
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
