
apiVersion: v2
name: external-dns
description: A Helm chart for Kubernetes

type: application

version: 0.1.0

appVersion: "1.0"

dependencies:
- name: external-dns
  version: ~5.4.4
  repository:  https://charts.bitnami.com/bitnami